
-- DROP DATABASE database1;
CREATE DATABASE database1 DEFAULT CHARACTER SET utf8mb4;

CREATE USER 'user1'@'localhost' IDENTIFIED BY 'password1';
GRANT ALL PRIVILEGES ON database1.* TO 'user1'@'localhost';
FLUSH PRIVILEGES;

USE database1;
-- DROP TABLE test1;
CREATE TABLE test1(test1_id BIGINT NOT NULL AUTO_INCREMENT, col01 TINYINT unsigned NOT NULL, col02 SMALLINT unsigned NOT NULL, col03 INT unsigned, col04 BIGINT unsigned NOT NULL, col05 FLOAT NOT NULL, col06 DOUBLE NOT NULL, col07 VARCHAR(10) NOT NULL, col08 TEXT NOT NULL, col09 BLOB NOT NULL, col10 DATETIME NOT NULL, col11 INT NULL, col12 DATETIME NOT NULL, PRIMARY KEY(test1_id));
